version = 1

[[annotations]]
path = [
        ".gitignore",
        ".gitmodules",
]
SPDX-FileCopyrightText = "2025 CERN"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
        "test/adaptyst_results/2023*/**.data",
        "test/adaptyst_results/2023*/*/**.data",
]
SPDX-FileCopyrightText = "2023 CERN"
SPDX-License-Identifier = "CC-BY-4.0"
